Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision :shell, inline: "/vagrant/vagrant_bootstrap.sh", run: "always"
  config.vm.network "private_network", ip: "10.10.10.30"
end
