Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.synced_folder ".", "/MEAN_stack"
  config.vm.provision :shell, path: "vagrant_bootstrap.sh"
  config.vm.network "hostonly", ip: "10.10.10.10"
end
